"""empty message

Revision ID: 4977c2aa50a4
Revises: 43a07041e442
Create Date: 2025-02-07 23:49:32.356246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4977c2aa50a4'
down_revision = '43a07041e442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_diversity', schema=None) as batch_op:
        batch_op.drop_constraint('product_id', type_='foreignkey')
        batch_op.create_foreign_key('product_id', 'product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_diversity', schema=None) as batch_op:
        batch_op.drop_constraint('product_id', type_='foreignkey')
        batch_op.create_foreign_key('product_id', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
