"""empty message

Revision ID: 55d235bd10c0
Revises: 4e3306e9a4eb
Create Date: 2025-01-27 11:40:37.898711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d235bd10c0'
down_revision = '4e3306e9a4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_diversity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('memory', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('product_color', sa.VARCHAR(), nullable=True),
    sa.Column('product_memory', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='review_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_diversity')
    # ### end Alembic commands ###
