"""empty message

Revision ID: adc81d44446f
Revises: cfc97fd98378
Create Date: 2024-12-24 12:12:14.749634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc81d44446f'
down_revision = 'cfc97fd98378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('product_memory', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('product_memory')
        batch_op.drop_column('product_color')

    # ### end Alembic commands ###
