"""empty message

Revision ID: d5d32803c9f9
Revises: 55d235bd10c0
Create Date: 2025-02-01 15:07:24.798543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d32803c9f9'
down_revision = '55d235bd10c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    with op.batch_alter_table('product_diversity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('product_id', 'product', ['product_id'], ['id'])
        batch_op.drop_column('brand')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_diversity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('product_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('product_color', sa.VARCHAR(), nullable=True),
    sa.Column('product_memory', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='review_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
